config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'chatbot_intents#index'
  get 'chatbot_intents/consult_deposit', to: 'chatbot_intents#consult_deposit'
  get 'chatbot_intents/consult_indicators', to: 'chatbot_intents#consult_indicators'
  get 'chatbot_intents/deposit_details', to: 'chatbot_intents#deposit_details'
  get 'chatbot_intents/new_request_paper_rolls', to: 'chatbot_intents#new_request_paper_rolls'
  post 'chatbot_intents/request_paper_rolls', to: 'chatbot_intents#request_paper_rolls'
  get 'chatbot_intents/order_details', to: 'chatbot_intents#order_details'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  validates :email, uniqueness: true
  validates :rut, uniqueness: true
  validates_format_of :email, with: /@/
  has_many :deposits
  has_many :order_papers
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  validates :amount, numericality: { greater_than_or_equal_to: 0 }, presence: true
  belongs_to :client
  validates :client_id, uniqueness: { scope: :deposit_date }
end

app/models/order_paper.rb
class OrderPaper < ApplicationRecord
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }, presence: true
  belongs_to :client
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatbot_intents_controller.rb
class ChatbotIntentsController < ApplicationController
  include Paginable
  include Indicators
  before_action :find_client, only: %i[deposit_details request_paper_rolls]
  before_action :find_order, only: %i[order_details]

  PAPER_ROLL_PRICE = 700

  def consult_deposit; end

  def new_request_paper_rolls; end

  def index
    @clients = Client.all.page(current_page).per(per_page)
  end

  def deposit_details
    unless params[:deposit_date].present?
      response_with_notice('consult_deposit', t(:rut_date_validate))
      return
    end
    if @client.present?
      @deposit = @client.deposits.find_by(deposit_date: params[:deposit_date])
      response_with_notice('consult_deposit', t(:no_deposit)) unless @deposit.present?
    else
      response_with_notice('consult_deposit', t(:invalid_rut))
    end
  end

  def consult_indicators
    search_indicators
  end

  def request_paper_rolls
    if @client.present?
      quantity = params['quantity'].to_i
      delivery_address = params['delivery_address']
      deposit = @client.deposits.find_by(deposit_date: Date.tomorrow) # deposit of tomorrow
      if deposit.present?
        order_amount = quantity * PAPER_ROLL_PRICE
        if order_amount <= deposit.amount
          create_order(delivery_address, deposit, order_amount, quantity)
          redirect_to action: 'order_details', id: @order.id
        else
          response_with_notice('new_request_paper_rolls', t(:insufficient_amount))
        end
      end
    else
      response_with_notice('new_request_paper_rolls', t(:invalid_rut))
    end
  end

  def order_details
    respond_to do |format|
      format.html
      format.pdf do
        html = render_to_string(template: 'chatbot_intents/order_details.pdf.erb', layout: false, encoding: 'utf8',
                                locals: { order: @order })
        pdf = WickedPdf.new.pdf_from_string(html, orientation: 'Landscape')
        send_data(pdf, filename: "order_#{@order.id}.pdf", disposition: 'inline', margin: { left: 200, right: 0 })
      end
    end
  end

  private

  def find_client
    @client = Client.find_by(rut: params[:rut])
  end

  def find_order
    @order = OrderPaper.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = t(:no_order)
  end

  def create_order(delivery_address, deposit, order_amount, quantity)
    @order = OrderPaper.create! quantity: quantity, amount: order_amount,
                                delivery_address: delivery_address, client: @client
    deposit.amount = deposit.amount - order_amount
    deposit.save
  end

  def response_with_notice(action, message)
    redirect_to action: action
    flash[:notice] = message
  end
end

app/controllers/concerns/indicators.rb
module Indicators
  require 'net/http'
  require 'json'

  protected

  def search_indicators
    # Indicators from https://mindicador.cl/api
    @indicators = {}
    uri = URI('https://mindicador.cl/api')
    res = Net::HTTP.get_response(uri)
    data = JSON.parse(res.body)
    @indicators['dolar'] = data['dolar']
    @indicators['utm'] = data['utm']
    @indicators['uf'] = data['uf']
  end
end

app/controllers/concerns/paginable.rb
module Paginable
  protected

  def current_page
    (params[:page] || 1).to_i
  end

  def per_page
    (params[:per_page] || 10).to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatbot_intents_helper.rb
module ChatbotIntentsHelper
end

app/views/chatbot_intents/consult_deposit.html.erb
<%= render(partial: 'headers/header_chatbot') %>
<%= form_tag(chatbot_intents_deposit_details_path, method: :get) do %>
  <div class="box">
    <p><strong>Indique Rut y Fecha</strong></p>
    <%= label_tag "Rut" %>
    <br>
    <%= text_field_tag "rut" %>
    <br>
    <%= label_tag "fecha" %>
    <br>
    <%= date_field_tag "deposit_date" %>
  </div>
  <br>

  <%= submit_tag "OK" %>
  <%= link_to "Volver", :controller => 'chatbot_intents', :action => 'index' %>
<% end %>

app/views/chatbot_intents/consult_indicators.html.erb
<%= render(partial: 'headers/header_chatbot') %>

<div class="box">
  <p><strong>Indicadores (https://mindicador.cl/api)</strong></p>
  <div class="container-body">
    <table class="list">
      <thead>
      <tr>
        <th>Nombre</th>
        <th>Code</th>
        <th>Fecha</th>
        <th>Monto</th>
        <th>Unidad de Medida</th>
      </tr>
      </thead>
      <tbody>
      <% @indicators.each do |key, value| %>
        <tr>
          <td class="name"><span><%= value['nombre'] %></span></td>
          <td class="name"><span><%= value['codigo'] %></span></td>
          <td class="name"><span><%= value['fecha'].to_date.strftime("%m/%d/%Y") %></span></td>
          <td class="name"><span><%= value['valor'] %></span></td>
          <td class="name"><span><%= value['unidad_medida'] %></span></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/chatbot_intents/deposit_details.html.erb
<%= render(partial: 'headers/header_chatbot') %>

<% if @deposit.present? %>
  <div class="autoscroll">
    <h2>Información del depósito</h2>
    <div class="container-body">
      <table class="list">
        <thead>
        <tr>
          <th>RUT</th>
          <th>Cliente</th>
          <th>Fecha de abono</th>
          <th>Monto</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td class="name"><span><%= @deposit.client.rut %></span></td>
          <td class="name"><span><%= @deposit.client.name %></span></td>
          <td class="name"><span><%= @deposit.deposit_date.strftime("%m/%d/%Y") %></span></td>
          <td class="name"><span><%= @deposit.amount %></span></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <p class="nodata">No hay datos</p>
<% end %>

app/views/chatbot_intents/index.html.erb
<%= render(partial: 'headers/header_chatbot') %>
<%= stylesheet_link_tag 'chatbot_intents' %>

<% if @clients.any? %>
  <div class="autoscroll">
    <h2>Clientes</h2>
    <div class="container-body">
      <table class="list">
        <thead>
        <tr>
          <th>RUT</th>
          <th>Nombre</th>
          <th>Email</th>
        </tr>
        </thead>
        <tbody>
        <% @clients.each do |client| %>
          <tr>
            <td class="name"><span><%= client.rut %></span></td>
            <td class="name"><span><%= client.name %></span></td>
            <td class="name"><span><%= client.email %></span></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @clients %>
  </div>
<% else %>
  <p class="nodata">No hay datos</p>
<% end %>
<p class="flash-notice"><%= params[:notice] %></p>

app/views/chatbot_intents/new_request_paper_rolls.html.erb
<%= render(partial: 'headers/header_chatbot') %>
<%= form_tag(chatbot_intents_request_paper_rolls_path, method: :post) do %>
  <div class="box">
    <p><strong>Indique Rut del cliente y cantidad de rollos de papel del pedido</strong></p>
    <%= label_tag "Rut" %>
    <br>
    <%= text_field_tag "rut" %>
    <br>
    <%= label_tag "Cantidad" %>
    <br>
    <%= text_field_tag "quantity" %>
    <br>
    <%= label_tag "Dirección de entrega" %>
    <br>
    <%= text_area_tag "delivery_address" %>
  </div>
  <%= submit_tag "Solicitar" %>
  <%= link_to "Volver", :controller => 'chatbot_intents', :action => 'index' %>
<% end %>

app/views/chatbot_intents/order_details.html.erb
<%= render(partial: 'headers/header_chatbot') %>
<%= stylesheet_link_tag 'chatbot_intents' %>

<% if @order.present? %>
  <div class="autoscroll">
    <h3>Información de la orden de compra</h3>
    <div class="container-body">
      <table class="list">
        <thead>
        <tr>
          <th>RUT</th>
          <th>Cliente</th>
          <th>Cantidad</th>
          <th>Monto</th>
          <th>Dirección de entrega</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td class="name"><span><%= @order.client.rut %></span></td>
          <td class="name"><span><%= @order.client.name %></span></td>
          <td class="name"><span><%= @order.quantity %></span></td>
          <td class="name"><span><%= @order.amount %></span></td>
          <td class="name"><span><%= @order.delivery_address %></span></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
  <%= link_to "Exportar PDF", chatbot_intents_order_details_path(id: @order.id, format: :pdf) %>
<% end %>

app/views/chatbot_intents/order_details.pdf.erb
<style type="text/css">
  h2.title {
    text-align: center
  }

  .date {
    padding-right: 20%;
    font-weight: bold;
  }

  /*    .container-body {
        border: 2px solid #000;
      }*/
  /***** Tables *****/
  table.list, .table-list {
    border: 1px solid #e4e4e4;
    border-collapse: collapse;
    width: 100%;
    margin-bottom: 4px;
  }

  table.list th, .table-list-header {
    background-color: #EEEEEE;
    padding: 4px;
    white-space: nowrap;
    font-weight: bold;
  }

  table.list td {
    text-align: center;
    vertical-align: top;
    padding-right: 10px;
  }

  table.list td.id {
    width: 2%;
    text-align: center;
  }

  table.list td.name, table.list td.ni, table.list td.subject, table.list td.comments, table.list td.roles {
    text-align: left;
  }

  table.list td.tick {
    width: 15%
  }

  table.list td.checkbox {
    width: 15px;
    padding: 2px 0 0 0;
  }

  table.list td.checkbox input {
    padding: 0px;
  }

  table.list td.buttons, div.buttons {
    width: 15%;
    white-space: nowrap;
    text-align: right;
  }

  table.list td.buttons a, div.buttons a {
    margin-right: 0.6em;
  }

  table.list td.buttons img, div.buttons img {
    vertical-align: middle;
  }

  table.list td.reorder {
    width: 15%;
    white-space: nowrap;
    text-align: center;
  }

  table.list table.progress td {
    padding-right: 0px;
  }

  table.list caption {
    text-align: left;
    padding: 0.5em 0.5em 0.5em 0;
  }

  #role-permissions-trackers table.list th {
    white-space: normal;
  }

  .table-list-cell {
    display: table-cell;
    vertical-align: top;
    padding: 2px;
  }

  table.list tbody td, tr:hover td {
    border: solid 1px #ddd;
  }

  table.list thead th {
    border: 1px solid #ddd;
  }

  table.list thead th.short {
    max-width: 64px;
    word-wrap: break-word;
    text-align: center;
    white-space: normal;
  }

  table.list thead th.medium {
    max-width: 90px;
    word-wrap: break-word;
    text-align: center;
    white-space: normal;
  }

</style>
<meta charset="utf-8">
<div class="container">
  <div class="container-header">
    <h2 class="title"> Resumen de orden de compra</h2>
    <p>
      Fecha <span class="date"><%= order.created_at %></span>
    </p>
  </div>
  <div class="container-body">
    <table class="list">
      <thead><tr>
        <th>Cliente</th>
        <th>Cantidad</th>
        <th>Dirección de entrega</th>
        <th>Monto</th>
      </tr></thead>
      <tbody>
        <% if order.present? %>
            <tr>
              <td class="name"><span><%= order.client.name %></span></td>
              <td class="name"><span><%= order.quantity %></span></td>
              <td class="name"><span><%= order.delivery_address %></span></td>
              <td class="name"><span><%= order.amount %></span></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/chatbot_intents/request_paper_rolls.html.erb
<%= render(partial: 'headers/header_chatbot') %>

<% if @order.present? %>
  <div class="autoscroll">
    <h2>Información de la orden de compra</h2>
      <%= @order.client.name %>
      <%= @order.quantity %>
      <%= @order.amount %>
      <%= @order.delivery_address %>
  </div>

<% else %>
  <p class="nodata">No hay datos</p>
<% end %>

app/views/chatbot_intents/request_paper_rolls.pdf.erb
<style type="text/css">
  h2.title {
    text-align: center
  }

  .date {
    padding-right: 20%;
    font-weight: bold;
  }

  /*    .container-body {
        border: 2px solid #000;
      }*/
  /***** Tables *****/
  table.list, .table-list {
    border: 1px solid #e4e4e4;
    border-collapse: collapse;
    width: 100%;
    margin-bottom: 4px;
  }

  table.list th, .table-list-header {
    background-color: #EEEEEE;
    padding: 4px;
    white-space: nowrap;
    font-weight: bold;
  }

  table.list td {
    text-align: center;
    vertical-align: top;
    padding-right: 10px;
  }

  table.list td.id {
    width: 2%;
    text-align: center;
  }

  table.list td.name, table.list td.ni, table.list td.subject, table.list td.comments, table.list td.roles {
    text-align: left;
  }

  table.list td.tick {
    width: 15%
  }

  table.list td.checkbox {
    width: 15px;
    padding: 2px 0 0 0;
  }

  table.list td.checkbox input {
    padding: 0px;
  }

  table.list td.buttons, div.buttons {
    width: 15%;
    white-space: nowrap;
    text-align: right;
  }

  table.list td.buttons a, div.buttons a {
    margin-right: 0.6em;
  }

  table.list td.buttons img, div.buttons img {
    vertical-align: middle;
  }

  table.list td.reorder {
    width: 15%;
    white-space: nowrap;
    text-align: center;
  }

  table.list table.progress td {
    padding-right: 0px;
  }

  table.list caption {
    text-align: left;
    padding: 0.5em 0.5em 0.5em 0;
  }

  #role-permissions-trackers table.list th {
    white-space: normal;
  }

  .table-list-cell {
    display: table-cell;
    vertical-align: top;
    padding: 2px;
  }

  table.list tbody td, tr:hover td {
    border: solid 1px #ddd;
  }

  table.list thead th {
    border: 1px solid #ddd;
  }

  table.list thead th.short {
    max-width: 64px;
    word-wrap: break-word;
    text-align: center;
    white-space: normal;
  }

  table.list thead th.medium {
    max-width: 90px;
    word-wrap: break-word;
    text-align: center;
    white-space: normal;
  }

</style>
<meta charset="utf-8">
<div class="container">
  <div class="container-header">
    <h2 class="title"> Resumen de orden de compra</h2>
    <p>
      Fecha <span class="date"><%= order.created_at %></span>
    </p>
  </div>
  <div class="container-body">
    <table class="list">
      <thead><tr>
        <th>Cliente</th>
        <th>Cantidad</th>
        <th>Dirección de entrega</th>
        <th>Monto</th>
      </tr></thead>
      <tbody>
        <% if order.present? %>
            <tr>
              <td class="name"><span><%= order.client.name %></span></td>
              <td class="name"><span><%= order.quantity %></span></td>
              <td class="name"><span><%= order.delivery_address %></span></td>
              <td class="name"><span><%= order.amount %></span></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/headers/_header_chatbot.html.erb
<div class="tabs">
  <ul>
      <li>
        <%= link_to "Listado de Clientes",
                    {controller: :chatbot_intents, action: 'index'},
                    class: 'selected'
        %>
      </li>
      <li>
        <%= link_to "Consulta de Depósito",
                    {controller:  :chatbot_intents, action: 'consult_deposit'}
        %>
      </li>
      <li>
        <%= link_to "Consultar Indicadores de hoy",
                    {controller:  :chatbot_intents, action: 'consult_indicators'}
        %>
      </li>
      <li>
        <%= link_to "Solicitar Rollos de papel",
                    {controller:  :chatbot_intents, action: 'new_request_paper_rolls'}
        %>
      </li>


  </ul>

  <div class="tabs-buttons" style="display:none;">
    <button class="tab-left" onclick="moveTabLeft(this);"></button>
    <button class="tab-right" onclick="moveTabRight(this);"></button>
  </div>
  <script>
      $(document).ready(displayTabsButtons);
      $(window).resize(displayTabsButtons);
  </script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatbot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>
  </body>
</html>